name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multimodalmap-voicerecognition
          environment_name: multimodalmap-voicerecognition-dev
          version_label: github-${{ github.sha }}
          region: us-west-2
          zip_file: voice_recognition.zip # if you're deploying as a zip archive, otherwise it will zip the current directory
